spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update

app:
  data-loader:
    enabled: true
  openapi:
    public-enabled: true
  security:
    refresh-cookie:
      secure: false
